# Generated by Django 3.2 on 2022-04-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationreservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oproom',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
