# Generated by Django 3.2 on 2022-06-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationreservation', '0002_auto_20220409_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='time_slot',
        ),
        migrations.AlterField(
            model_name='operation',
            name='department_id',
            field=models.CharField(default='True', max_length=10),
        ),
        migrations.AlterField(
            model_name='operation',
            name='doctor_name',
            field=models.CharField(default='True', max_length=70),
        ),
        migrations.AlterField(
            model_name='operation',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='emergency',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='patient_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='room_id',
            field=models.CharField(default='True', max_length=10),
        ),
    ]
