# Generated by Django 3.2 on 2022-06-28 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationreservation', '0004_alter_operation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 28)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='department_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='operation',
            name='doctor_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='operation',
            name='room_id',
            field=models.CharField(max_length=10),
        ),
    ]
