# Generated by Django 3.2 on 2022-06-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationreservation', '0005_auto_20220628_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='department_id',
            field=models.CharField(default='True', max_length=10),
        ),
        migrations.AlterField(
            model_name='operation',
            name='doctor_name',
            field=models.CharField(default='True', max_length=70),
        ),
        migrations.AlterField(
            model_name='operation',
            name='room_id',
            field=models.CharField(default='True', max_length=10),
        ),
    ]
