# Generated by Django 3.2 on 2022-06-29 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationreservation', '0006_auto_20220628_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 29)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='department_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='operation',
            name='doctor_name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='operation',
            name='patient_id',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='room_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
