# Generated by Django 3.2 on 2022-07-01 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationreservation', '0007_auto_20220629_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 1)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='department_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
