# Generated by Django 3.2 on 2022-07-03 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operationreservation', '0009_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='oproom',
            name='operation',
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.date(2022, 7, 3)),
        ),
    ]
